import { Readable } from 'stream';
import { OpenAI, toFile } from 'openai';

import { ImagePrompt } from '../models/image-prompt';
import {
  ImageData,
  ImageResponse,
  ResponseMetadata
} from '../models/image-response';
import type { IUniversalAIProvider } from '../models/universal-ai-provider';

/**
 * OpenAIProvider is an implementation of the IUniversalAIProvider interface.
 * It simulates generating an image based on a given prompt and returns a structured response.
 * This class interacts with the OpenAI API to generate images.
 */
export class OpenAIProvider implements IUniversalAIProvider {
  constructor(private readonly client: OpenAI) {}

  async generateImage(prompt: ImagePrompt): Promise<ImageResponse> {
    const startTime = Date.now(); // start timer before API call

    // TODO: Use argument read the real file base on what you need.
    // More see the `ai-openai-provider.test.ts`
    // const imageFile = 'src/meme.png';
    const imageStream = prompt.getArgument<Readable>('img');
    if (!imageStream || !(imageStream instanceof Readable)) {
      throw new Error('Image argument is missing or not a Readable Stream.');
    }
    const name = prompt.getArgument<string>('name');
    const MIME = prompt.getArgument<string>('type');
    if (!name || !MIME) {
      throw new Error('Image name/type arguments are required (name, type).');
    }

    // these come FROM the prompt, not hardcoded
    const width = prompt.getArgument<number>('width') || 512;
    const height = prompt.getArgument<number>('height') || 512;

    // Call the OpenAI API to generate an image and return a response
    const apiResponse = await this.client.images.edit({
      prompt: prompt.getRawPrompt(),
      model: 'gpt-image-1-mini',
      image: await toFile(imageStream, name, {
        type: MIME
      })
    });

    // check if the API response contains the expected data(list of generated images), in our case the list of len = 1
    if (!apiResponse.data || apiResponse.data.length === 0) {
      throw new Error('No image generated by OpenAI API');
    }

    // extract the first image from the response, and check if it contains a URL
    const image = apiResponse.data[0];
    if (!image) {
      throw new Error('No URL returned from OpenAI API');
    }

    // extract the base64 string from the image data, and check if it exists
    const b64 = image.b64_json;
    if (!b64) {
      throw new Error('No image data returned from OpenAI API');
    }

    // fetch the image data as bytes using the base64 string, and construct the ImageResponse object to return
    const imageData = new ImageData(
      Buffer.from(b64, 'base64'),
      'png',
      width,
      height
    );

    const metaData = new ResponseMetadata(
      Date.now() - startTime,
      'gpt-image-1-mini',
      'success'
    );

    return new ImageResponse(imageData, metaData);
  }
}
