import type { Stream } from 'stream';

import type { StorageStrategy } from './file-storage';
import { FileRecord, type FileRepositoryOperator } from './file-system';
import type { IDGenerator } from './id-generator';

/**
 * non-persistent, in-memory implementation of `FileRepositoryOperator`.
 * all records are lost when the process restarts; intended for development
 * and testing only.
 */
export class InMemoryFileRepository implements FileRepositoryOperator {
  private records = new Map<string, FileRecord>();
  private idGenerator: IDGenerator;

  constructor(idGenerator: IDGenerator) {
    this.idGenerator = idGenerator;
  }

  /**
   * creates a `FileRecord` from the supplied metadata and stores it in memory.
   * uses `metadata.id` when provided (e.g. pre-generated by the controller);
   * falls back to the injected `IDGenerator` otherwise.
   * the actual file bytes are not stored here — persistence is the
   * responsibility of the `StorageStrategy`.
   */
  saveFile(
    file: Buffer | Stream,
    metadata: Partial<FileRecord>,
    strategy: StorageStrategy
  ): FileRecord {
    const id = metadata.id ?? this.idGenerator.generate();
    const record = new FileRecord(
      id,
      metadata.filename ?? '',
      metadata.localPath ?? '',
      metadata.type ?? '',
      metadata.create ?? new Date(),
      metadata.matedata ?? {}
    );
    this.records.set(id, record);
    return record;
  }

  getFileById(id: string): FileRecord | undefined {
    return this.records.get(id);
  }

  getFileStream(id: string, strategy: StorageStrategy): Stream | undefined {
    const record = this.records.get(id);
    if (!record) return undefined;
    let stream: Stream | undefined;
    strategy.read(record.filename).then((s) => {
      stream = s;
    });
    return stream;
  }
}
