import { Readable } from 'stream';
import type { Request, Response } from 'express';

import type { StorageStrategy } from '../models/file-storage';
import type { FileRecord, FileRepositoryOperator } from '../models/file-system';
import { ImagePrompt } from '../models/image-prompt';
import type { IUniversalAIProvider } from '../models/universal-ai-provider';

// jsdoc comment for the AIController class
/**
 * AIController is responsible for handling AI-related requests, specifically for generating images based on prompts.
 * It uses a Universal AI provider to generate images and a file repository to store the generated images.
 *
 * @class AIController
 * @constructor
 * @param {IUniversalAIProvider} aiGenerator - An instance of a Universal AI provider for generating images.
 * @param {FileRepositoryOperator} fileRepo - An instance of a file repository operator for managing file storage.
 * @param {StorageStrategy} strategy - The storage strategy to use for saving generated images.
 * @method generateResponse - Handles the incoming request to generate an image based on a prompt and returns the result.
 * Request body should contain:
 * - prompt: A string describing the image to be generated.
 * - imageId: A string representing the ID of an existing image file to be used as a reference for generation.
 * Response will contain:
 * - id: The ID of the generated image file.
 * - url: The URL or local path to access the generated image.
 * Error handling is implemented to return appropriate status codes and messages for invalid input or server errors.
 */
export class AIController {
  // Use Dependency Injection for UniversalAI instead of the actual implementation.
  constructor(
    private readonly aiGenerator: IUniversalAIProvider,
    private readonly fileRepo: FileRepositoryOperator,
    private readonly strategy: StorageStrategy
  ) {}
  async generateResponse(req: Request, res: Response) {
    try {
      const { prompt, imageId } = req.body;
      // check prompt
      if (typeof prompt !== 'string' || prompt.trim().length === 0) {
        return res.status(400).json({ error: 'Prompt is required' });
      }

      // check file id of the passed image
      if (!imageId || typeof imageId !== 'string') {
        return res.status(400).json({ error: 'Valid imageId is required' });
      }

      const existingFile = this.fileRepo.getFileById(imageId);
      if (!existingFile) {
        return res.status(404).json({ error: 'Image not found' });
      }

      const imagePrompt = new ImagePrompt(prompt);
      imagePrompt.setArgument(
        'img',
        await this.fileRepo.getFileStream(imageId, this.strategy)
      );
      imagePrompt.setArgument('name', existingFile.filename);
      imagePrompt.setArgument('type', existingFile.type);

      imagePrompt.parseRawPromptToArgs();
      const response = await this.aiGenerator.generateImage(imagePrompt);

      // save the file that generated by AI to local.
      const file = await this.fileRepo.saveFile(
        Buffer.from(response.getImage().payload),
        {
          type: response.getImage().format
        } as FileRecord,
        this.strategy
      );

      res.status(200).json({
        id: file.id,
        url: file.localPath || (await this.strategy.resolvePath(file.id || ''))
      });
    } catch (error) {
      console.error('Failed to generate AI response', error);
      res.status(500).json({ error: 'Failed to generate AI response' });
    }
  }
}
